#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PATTERN="^(feature|hotfix|release|bugfix|improvement)/NFG-[0-9]+-.+"

if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
  echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
  echo "Naming convention: (feature|hotfix|release|bugfix|improvement)/NFG-<issue-number>-<short-description>"
  exit 1
fi
